### ISSUE TITLE
Sample Clip for  RX100M7 and/or DSC-RX0M2

### ISSUE THREAD

**Issue by acgourley** [SK-Hardwired/xavc_rtmd2srt#5]
Hello, this project is very cool, thanks for sharing your work 🙏

I wanted to test it out on some clips before buying the cameras myself, is there a sample clip for either RX100M7 and/or DSC-RX0M2 with acc/gyro data? Or, if that isn't possible, example output of the data as exported from the clips would be useful. Thank you!

**Comment by SK-Hardwired** [comment]
I have no ones for this time. Sorry. But there are a lot of reviews on Internet already, you can find source video files.
